server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/ms-email
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  rabbitmq:
    addresses: amqps://xgvavwcx:Z45HPbMVZcxYgE3YKRxdcYkLoSJ0Jlfq@beaver.rmq.cloudamqp.com/xgvavwcx
    queue: ms.email